### ISSUE TITLE
ViewID AllocatedID: X Not Found On Reset Game

### ISSUE THREAD

**Issue by mattm401** [VacuumGames/tunnelers-unified#12]
Having wrapped up #5; I am still looking at what in the game is failing when the system resets... I am wondering if your trying to access objects that have been deleted. These are the errors that I presently see when the game restarts. I can look this up when my pull request is integrated! I think most of these errors are related except the missing object reference issue... that could be another thing.

![viewid allocation issues](https://cloud.githubusercontent.com/assets/1121334/4603921/4825fc34-517f-11e4-8517-a25b783172e1.png)

**Comment by DoctorJellyface** [comment]
@mattm401 could you check if this is working? I implemented a whole new system of destroying game objects, so it _should_ be fixed. Thanks!

**Comment by DoctorJellyface** [comment]
Hm, this is trickier than I thought. I'll remove the milestone, since it isn't a showstopping bug, and users won't really notice unless they check the log.

**Comment by DoctorJellyface** [comment]
This is gonna be fixed by UNET too, so closing.
